python tools/test.py configs/ultra_sound/reppoints/X-101-FPN-DCN/gist514_split0_reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck+head_2x_coco.py work_dirs/gist514_split0_reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck+head_2x_coco/latest.pth --eval bbox vanilla --show-dir playground/usd/gist514_split0_reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck+head_2x_coco/show_results/split0 2>&1 | tee work_dirs/gist514_split0_reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck+head_2x_coco/test.log

python tools/test.py configs/ultra_sound/reppoints/X-101-FPN-DCN/gist514_split1_reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck+head_2x_coco.py work_dirs/gist514_split1_reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck+head_2x_coco/latest.pth --eval bbox vanilla --show-dir playground/usd/gist514_split1_reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck+head_2x_coco/show_results/split1 2>&1 | tee work_dirs/gist514_split1_reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck+head_2x_coco/test.log

python tools/test.py configs/ultra_sound/reppoints/X-101-FPN-DCN/gist514_split2_reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck+head_2x_coco.py work_dirs/gist514_split2_reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck+head_2x_coco/latest.pth --eval bbox vanilla --show-dir playground/usd/gist514_split2_reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck+head_2x_coco/show_results/split2 2>&1 | tee work_dirs/gist514_split2_reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck+head_2x_coco/test.log

python tools/test.py configs/ultra_sound/reppoints/X-101-FPN-DCN/gist514_split3_reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck+head_2x_coco.py work_dirs/gist514_split3_reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck+head_2x_coco/latest.pth --eval bbox vanilla --show-dir playground/usd/gist514_split3_reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck+head_2x_coco/show_results/split3 2>&1 | tee work_dirs/gist514_split3_reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck+head_2x_coco/test.log

python tools/test.py configs/ultra_sound/reppoints/X-101-FPN-DCN/gist514_split4_reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck+head_2x_coco.py work_dirs/gist514_split4_reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck+head_2x_coco/latest.pth --eval bbox vanilla --show-dir playground/usd/gist514_split4_reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck+head_2x_coco/show_results/split4 2>&1 | tee work_dirs/gist514_split4_reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck+head_2x_coco/test.log
